import type { Metadata } from "next";
import { Nunito } from "next/font/google";

import NavBar from "@/components/NavBar";

import "./globals.css";

const nunito = Nunito({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Whovium",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} antialiased`}>
        <NavBar />
        <div>{children}</div>
      </body>
    </html>
  );
}
