import type { Metadata } from "next";

import { nunito } from "@/lib/fonts";

import "./globals.css";

import ColoredBackground from "@/components/colored-background";
import NavBarLoginProvider from "@/components/nav-bar-login-provider";

export const metadata: Metadata = {
  title: "Whovium",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} antialiased`}>
        <ColoredBackground>
          <NavBarLoginProvider />
          {children}
        </ColoredBackground>
      </body>
    </html>
  );
}
